services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak-estudo
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak/laboratorio-keycloak-realm.json:/opt/keycloak/data/import/laboratorio-keycloak-realm.json:ro
      - ./infra/keycloak/themes:/opt/keycloak/themes:ro

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-keycloak-estudo
    depends_on:
      - keycloak
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-keycloak-estudo
    depends_on:
      - keycloak
      - backend
    ports:
      - "5173:80"
