server:
  port: 8081

spring:
  application:
    name: keycloak-estudo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/laboratorio-keycloak}

laboratorio:
  keycloak:
    client-id: laboratorio-api
    policy-enforcer:
      enabled: true
      auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
      realm: ${KEYCLOAK_REALM:laboratorio-keycloak}
      resource: ${KEYCLOAK_POLICY_ENFORCER_RESOURCE:laboratorio-api}
      secret: ${KEYCLOAK_POLICY_ENFORCER_SECRET:laboratorio-api-secret}
    menu:
      url: ${KEYCLOAK_URL:http://localhost:8080}
      realm: ${KEYCLOAK_REALM:laboratorio-keycloak}
      client-id: ${KEYCLOAK_MENU_CLIENT_ID:laboratorio-menu}
      admin-client-id: ${KEYCLOAK_MENU_ADMIN_CLIENT_ID:laboratorio-menu}
      admin-client-secret: ${KEYCLOAK_MENU_ADMIN_CLIENT_SECRET:laboratorio-menu-secret}
